# Generated by Django 3.2.12 on 2022-02-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interestStorage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intereststoragemodel',
            name='endDate',
        ),
    ]
