# Generated by Django 3.2.12 on 2022-02-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interestStorage', '0003_intereststoragemodel_takenperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intereststoragemodel',
            name='takenPerson',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
