# Generated by Django 3.2.12 on 2022-02-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interestStorage', '0005_alter_intereststoragemodel_takenperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='intereststoragemodel',
            name='presentinterest',
            field=models.FloatField(default=0.0),
        ),
    ]
