# Generated by Django 3.2.12 on 2022-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(verbose_name='Born Date')),
                ('EndDate', models.DateField(verbose_name='Today Date')),
            ],
        ),
    ]
